version: '3.8'

services:
  db:
    image: postgres:16-alpine # Use a specific version of PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    volumes:
      - db_data:/var/lib/postgresql/data # Persist data in a named volume

volumes:
  db_data: